# Generated by Django 3.1.7 on 2021-04-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='phone_no',
            field=models.TextField(),
        ),
    ]
