# Generated by Django 3.1.7 on 2021-04-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0003_detail_uname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='uname',
            new_name='username',
        ),
    ]
