# Generated by Django 3.1.7 on 2021-04-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0004_auto_20210405_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='phone_no',
            field=models.TextField(unique=True),
        ),
    ]
